## Tutorial for Applying SoccerCPD to kloppy data

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import rpy2.robjects.packages as rpackages

from src.kloppy import Kloppy
from src.soccercpd import SoccerCPD

In [2]:
utils = rpackages.importr('utils')
utils.chooseCRANmirror(ind=1)
if not rpackages.isinstalled('gSeg'):
    utils.install_packages('gSeg')
rpackages.importr('gSeg')

rpy2.robjects.packages.Package as a <module 'gSeg'>

### Converting kloppy data into SoccerCPD format

In [3]:
data = pd.read_pickle("data/kloppy/sample_kloppy_file.pkl")
data

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,home_250042780_x,...,away_250105686_d,away_250105686_s,home_250132399_x,home_250132399_y,home_250132399_d,home_250132399_s,home_250146926_x,home_250146926_y,home_250146926_d,home_250146926_s
0,1,0 days 00:00:00.012526,0,In,None,-0.102770,-0.341014,0.218483,2.095251,-49.963806,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0 days 00:00:00.052526,1,In,None,-0.151340,-0.406673,0.213257,2.045958,-49.961674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0 days 00:00:00.092526,2,In,None,-0.192688,-0.466049,0.207688,1.814223,-49.958416,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0 days 00:00:00.132526,3,In,None,-0.216528,-0.521216,0.210978,1.504685,-49.957661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0 days 00:00:00.172526,4,In,Poland,-0.241989,-0.581856,0.210067,1.644357,-49.958775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133848,2,0 days 01:29:59.800000,134995,In,Poland,27.218003,12.678193,19.303439,5.200775,-25.788414,...,0.068274,1.706862,20.570339,6.820256,0.074778,1.869440,31.127176,-5.250538,0.026990,0.674758
133849,2,0 days 01:29:59.840000,134996,In,Poland,27.098542,12.785913,19.159118,5.402708,-25.770994,...,0.070400,1.760004,20.541334,6.891814,0.077213,1.930313,31.119009,-5.224920,0.026888,0.672212
133850,2,0 days 01:29:59.880000,134997,In,Poland,26.979120,12.892536,19.001372,5.618840,-25.753012,...,0.071731,1.793281,20.511772,6.965704,0.079585,1.989621,31.109913,-5.198496,0.027946,0.698655
133851,2,0 days 01:29:59.920000,134998,In,Poland,26.859591,12.998185,18.830347,5.846915,-25.734995,...,0.075364,1.884089,20.481655,7.040879,0.080989,2.024713,31.101923,-5.171621,0.028037,0.700928
133852,2,0 days 01:29:59.960000,134999,In,Poland,26.739812,13.102983,18.646193,6.084951,-25.718691,...,0.080502,2.012541,20.450691,7.116075,0.081321,2.033035,31.096189,-5.144443,0.027777,0.694423

In [4]:
kloppy = Kloppy(data)
kloppy.preprocess_times()
kloppy.round_change_times()
kloppy.label_player_periods()
input_data = kloppy.convert_to_soccercpd_input()
input_data

                      datetime  team  player_id  player_period  session     time          x          y     speed
0      2024-01-01 01:00:00.000  away  250002096              1        1     0.00   0.233449 -14.192799  0.000000
1      2024-01-01 01:00:00.040  away  250002096              1        1     0.04   0.284003 -14.194001  1.264207
2      2024-01-01 01:00:00.080  away  250002096              1        1     0.08   0.335943 -14.194717  1.298633
3      2024-01-01 01:00:00.120  away  250002096              1        1     0.12   0.393036 -14.193744  1.427516
4      2024-01-01 01:00:00.160  away  250002096              1        1     0.16   0.458015 -14.194160  1.624524
...                        ...   ...        ...            ...      ...      ...        ...        ...       ...
134995 2024-01-01 02:29:59.800  home  250146926              5        2  2699.80  31.127176  -5.250538  0.674758
134996 2024-01-01 02:29:59.840  home  250146926              5        2  2699.84  31.119009  -5.224920  0.672212
134997 2024-01-01 02:29:59.880  home  250146926              5        2  2699.88  31.109913  -5.198496  0.698655
134998 2024-01-01 02:29:59.920  home  250146926              5        2  2699.92  31.101923  -5.171621  0.700928
134999 2024-01-01 02:29:59.960  home  250146926              5        2  2699.96  31.096189  -5.144443  0.694423

[3645000 rows x 9 columns]

### Formation detection per team

In [5]:
team = "away"  # Choose among home and away
team_data = input_data[input_data["team"] == team]
cpd = SoccerCPD(team_data)
cpd.run()

------------------------- Session 1 --------------------------
               session            start_dt              end_dt
player_period
1                    1 2024-01-01 01:00:00 2024-01-01 01:45:00

* Step 1: Frame-by-frame role assignment using RoleRep
- Cost after iteration 1: 6.285
- Cost after iteration 2: 6.169
- Cost after iteration 3: 6.136
- Cost after iteration 4: 6.099
- Cost after iteration 5: 6.091
- Cost after iteration 6: 6.091
Iteration finished since there are no significant changes.

* Step 2: FormCPD based on role-adjacency matrices
Applying g-segmentation to the sequence between 01:00:00 and 01:44:22...
Generalized edge-count statistic (a) :
  Estimated change-point location: 1872
  Test statistic: 767.6692
  Approximated p-value: 1.921233e-164
Generalized edge-count statistic (u) :
  Estimated change-point location: 1842
  Test statistic: 1678.541
  Approximated p-value: 0
Change-point insignificant: The formation is not changed.

Detected formation change-points:
[]

* Step 3: RoleCPD per formation period based on role permutations

RoleCPD for the formation period 1:
Applying g-segmentation to the sequence between 01:00:00 and 01:44:22...
Generalized edge-count statistic (a) :
  Estimated change-point location: 966
  Test statistic: 7630.599
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 966
  Test statistic: 102647.6
  Approximated p-value: 0
A significant fine-tuned change-point at 01:17:48.
- Frequent permutations before 01:17:48:
[('[ 1  6  3  4  5  2  7  8  9 10]', 432),
 ('[10  6  3  4  5  2  7  8  9  1]', 67),
 ('[ 1 10  3  4  5  2  7  8  9  6]', 50),
 ('[ 1  2  3  4  5 10  7  8  9  6]', 31),
 ('[ 1  6  3  4  5  2  7  9  8 10]', 22)]
- Frequent permutations after 01:17:48:
[('[ 1  2  3  4  5  6  7  8  9 10]', 513),
 ('[10  2  3  4  5  6  7  8  9  1]', 100),
 ('[ 1  6  3  4  5  2  7  8  9 10]', 78),
 ('[ 6  2  3  4  5  1  7  8  9 10]', 34),
 ('[10  6  3  4  5  2  7  8  9  1]', 30)]

Applying g-segmentation to the sequence between 01:00:00 and 01:17:48...
Generalized edge-count statistic (a) :
  Estimated change-point location: 608
  Test statistic: 820.9267
  Approximated p-value: 3.222861e-176
Generalized edge-count statistic (u) :
  Estimated change-point location: 607
  Test statistic: 2098.923
  Approximated p-value: 0
Change-point insignificant: The formation is not changed.

Applying g-segmentation to the sequence between 01:17:48 and 01:44:22...
Generalized edge-count statistic (a) :
  Estimated change-point location: 747
  Test statistic: 2089.877
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 511
  Test statistic: 12134.63
  Approximated p-value: 0
Change-point insignificant: The formation is not changed.

Detected role change-points:
[Timestamp('2024-01-01 01:17:45')]

------------------------- Session 2 --------------------------
               session            start_dt              end_dt
player_period
2                    2 2024-01-01 01:45:00 2024-01-01 02:07:20
3                    2 2024-01-01 02:07:20 2024-01-01 02:30:00

* Step 1: Frame-by-frame role assignment using RoleRep
- Cost after iteration 1: 6.414
- Cost after iteration 2: 6.248
- Cost after iteration 3: 6.236
- Cost after iteration 4: 6.234
Iteration finished since there are no significant changes.

* Step 2: FormCPD based on role-adjacency matrices
Applying g-segmentation to the sequence between 01:45:00 and 02:29:59...
Generalized edge-count statistic (a) :
  Estimated change-point location: 2272
  Test statistic: 1201.387
  Approximated p-value: 1.616404e-258
Generalized edge-count statistic (u) :
  Estimated change-point location: 924
  Test statistic: 1360.833
  Approximated p-value: 4.073185e-293
Change-point insignificant: One of the periods has not enough duration.

Detected formation change-points:
[]

* Step 3: RoleCPD per formation period based on role permutations

RoleCPD for the formation period 2:
Applying g-segmentation to the sequence between 01:45:00 and 02:29:59...
Generalized edge-count statistic (a) :
  Estimated change-point location: 2251
  Test statistic: 5255.488
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 718
  Test statistic: 12070.98
  Approximated p-value: 0
Change-point insignificant: One of the periods has not enough duration.

Detected role change-points:
[]

-------------------------------------------------------------------------
Formation Periods:
   session            start_dt              end_dt  duration
0        1 2024-01-01 01:00:00 2024-01-01 01:45:00    2700.0
1        2 2024-01-01 01:45:00 2024-01-01 02:30:00    2700.0

Role Periods:
   role_period  session            start_dt              end_dt  duration
0            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0
1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0
2            3        2 2024-01-01 01:45:00 2024-01-01 02:07:20    1340.0
3            4        2 2024-01-01 02:07:20 2024-01-01 02:30:00    1360.0

### Label assignment using precomputed formation clusters

In [6]:
form_summary = pd.read_pickle("data/form_summary.pkl")
role_summary = pd.read_csv("data/role_summary.csv", header=0)
cpd.label_roles(role_summary, form_summary)
cpd.role_labels

    1    2    3    4   5    6    7    8    9    10
1  LCF  RCM  RCB  RWB  CB  LCM  CDM  LCB  LWB  RCF
2  LCF  RCM  RCB  RWB  CB  LCM  CDM  LCB  LWB  RCF

In [7]:
cpd.form_periods

   form_period  session            start_dt              end_dt  duration                                             coords                                           edge_mat formation
0            1        1 2024-01-01 01:00:00 2024-01-01 01:45:00    2700.0  [[17.4302, 4.7377], [2.9593, -9.8385], [-12.00...  [[0.0, 0.3548, 0.013, 0.1729, 0.0146, 0.9577, ...       352
1            2        2 2024-01-01 01:45:00 2024-01-01 02:30:00    2700.0  [[16.2681, 4.7109], [3.3101, -9.8733], [-13.24...  [[0.0, 0.5053, 0.0178, 0.2436, 0.013, 0.9262, ...       352

In [8]:
cpd.role_summary[:20]

    player_period  form_period  role_period  session            start_dt              end_dt  duration  player_id  base_role        x        y aligned_role
0               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250002096          1  17.4302   4.7377          LCF
1               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250024370          6   4.7119   6.5702          LCM
2               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250056266          3 -12.0078  -9.7835          RCB
3               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250066342          4  -2.9213 -20.2577          RWB
4               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250070827          5 -12.5531   0.0657           CB
5               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250087872          2   2.9593  -9.8385          RCM
6               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250092129          7  -4.6658   1.1787          CDM
7               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250105681          8  -8.5793  13.4081          LCB
8               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250124155          9   2.4031  20.6587          LWB
9               1            1            1        1 2024-01-01 01:00:00 2024-01-01 01:17:45    1065.0  250166754         10  13.2229  -6.7394          RCF
10              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250002096          1  17.4302   4.7377          LCF
11              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250024370          2   2.9593  -9.8385          RCM
12              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250056266          3 -12.0078  -9.7835          RCB
13              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250066342          4  -2.9213 -20.2577          RWB
14              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250070827          5 -12.5531   0.0657           CB
15              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250087872          6   4.7119   6.5702          LCM
16              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250092129          7  -4.6658   1.1787          CDM
17              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250105681          8  -8.5793  13.4081          LCB
18              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250124155          9   2.4031  20.6587          LWB
19              1            1            2        1 2024-01-01 01:17:45 2024-01-01 01:45:00    1635.0  250166754         10  13.2229  -6.7394          RCF

### Saving results and visualization

In [9]:
cpd.save_stats(match_id=f"sample_{team}")

'./data/gseg_avg/form_summary/sample_away.pkl' saving done.
'./data/gseg_avg/role_summary/sample_away.csv' saving done.
'./data/gseg_avg/role_seq/sample_away.csv' saving done.

In [10]:
cpd.visualize(match_id=f"sample_{team}", role_labels=cpd.role_labels, save=True)

'./data/gseg_avg/viz_report/sample_away.png' saving done.